CREATE TABLE CUSTOMER(
  CUSTOMER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64),
  ADDRESS VARCHAR(64),
  COUNTRY VARCHAR(32),
  STATE VARCHAR(12),
  PHONE_NUMBER VARCHAR(24),
  CREATE_DATE DATE,
  UPDATE_DATE DATE,
  CREATE_USER VARCHAR(64),
  UPDATE_USER VARCHAR(64)
);